import { cloudEnabled, listenToAppData, saveAppData, watchAuthState, signInAdmin, signOutAdmin } from './firebase.js';
import { firebaseConfig } from './firebase-config.js';

const KEY = 'society-gramado-v1';
const initial = { fields:[], players:[], games:[], payments:[], pix:'' };
let state = cloudEnabled ? structuredClone(initial) : load();
let currentUser = null;
let stopDataListener = null;
let authMessage = '';
let page = 'dashboard';
let searchTerm = '';
let rosterGame = null;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(initial)}catch{return structuredClone(initial)}}
const RECEIPT_DB='society-gramado-receipts-v1';
function openReceiptDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(RECEIPT_DB,1);req.onupgradeneeded=()=>req.result.createObjectStore('files');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function saveLocalReceipt(file){if(file.size>5000000)throw new Error('O arquivo deve ter até 5 MB.');const db=await openReceiptDb(),key='r'+Date.now()+Math.random().toString(36).slice(2,7);await new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').put(file,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();return key}
async function readLocalReceipt(key){const db=await openReceiptDb();const value=await new Promise((resolve,reject)=>{const req=db.transaction('files').objectStore('files').get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});db.close();return value}
function openReceipt(ref){const popup=window.open('about:blank','_blank');readLocalReceipt(ref.slice('localreceipt:'.length)).then(file=>{if(!file){popup?.close();toast('Este comprovante está salvo somente no dispositivo onde foi anexado.');return}const url=URL.createObjectURL(file);if(popup)popup.location.href=url;setTimeout(()=>URL.revokeObjectURL(url),60000)}).catch(()=>{popup?.close();toast('Não foi possível abrir o comprovante neste dispositivo.')})}
function receiptCell(p){if(!p.receipt)return '—';if(p.receipt.startsWith('localreceipt:'))return `<button type="button" class="link" data-action="open-receipt" data-receipt="${esc(p.receipt)}">Abrir arquivo ↗</button>`;return `<a class="link" href="${esc(p.receipt)}" target="_blank" rel="noopener">Ver arquivo ↗</a>`}
function persist(){localStorage.setItem(KEY,JSON.stringify(state)); saveAppData(state).catch(()=>toast('Não foi possível sincronizar com Firebase. Confira as regras do Firestore.'));}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const brl=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const localDate=s=>s?new Date(`${s}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'}):'';
const initials=n=>String(n||'?').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const today = new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function upcoming(){return state.games.filter(g=>g.date>=today&&g.status!=='cancel').sort((a,b)=>a.date.localeCompare(b.date))[0]}
function field(id){return state.fields.find(f=>f.id===id)}
function paidCount(g){return (g.players||[]).filter(p=>p.paid).length}
function dueTotal(g){return (g.players||[]).reduce((sum,p)=>sum+(p.paid?0:Number(g.fee||0))+(g.foodFee&&p.foodWanted&&!p.foodPaid?Number(g.foodFee):0),0)}
function gameStatus(g){if(g.status==='closed')return '<span class="pill done">Encerrado</span>';if(g.status==='played')return '<span class="pill done">Realizado</span>';return '<span class="pill open">Inscrições abertas</span>'}
function navItem(id,icon,label){return `<button class="${page===id?'active':''}" data-page="${id}"><span class="ico">${icon}</span>${label}</button>`}
function render(){
 if(cloudEnabled && !currentUser) return renderLogin();
 document.querySelector('#app').className='shell';
 const g=upcoming();
 document.querySelector('#app').innerHTML=`<aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-mark">⚽</div><div><strong>Society Gramado</strong><small>Gestão do futebol</small></div></div><div class="nav-label">Menu principal</div><nav class="nav">${navItem('dashboard','▦','Visão geral')}${navItem('games','◷','Jogos')}${navItem('players','♙','Participantes')}${navItem('fields','▤','Gramados')}${navItem('finance','＄','Pagamentos')}${navItem('settings','⚙','Configurações')}</nav><div class="sidebar-bottom"><div class="cloud-status"><span class="cloud-dot" style="background:${cloudEnabled?'#92d85b':'#e9a442'}"></span>${cloudEnabled?'Firebase identificado':'Modo de demonstração'}<br>${cloudEnabled?'Serviços e acesso seguro pendentes':'Os dados ficam neste navegador até configurar o Firebase.'}</div></div></aside><main class="main"><header class="topbar"><div class="crumb"><button class="btn mobile-menu" id="menuBtn">☰</button> &nbsp; Futebol Society / <b>${pageTitle()}</b></div><div class="user"><div class="avatar">MF</div><span class="user-name">Administrador</span>${cloudEnabled?'<button class="btn small" data-action="logout">Sair</button>':''}</div></header><section class="page">${pageBody(g)}</section></main>`;
}
function renderLogin(message=''){
 const root=document.querySelector('#app');root.className='login-screen';
 root.innerHTML=`<section class="login-card"><div class="brand-mark login-mark">⚽</div><div class="eyebrow">ÁREA ADMINISTRATIVA</div><h1>Society Gramado</h1><p class="sub">Entre com o e-mail e a senha do administrador.</p><form id="loginForm"><label for="loginEmail">E-mail</label><input id="loginEmail" name="email" type="email" autocomplete="username" required><label for="loginPassword">Senha</label><input id="loginPassword" name="password" type="password" autocomplete="current-password" required><div class="login-error" role="alert">${esc(message)}</div><button class="btn primary login-submit" type="submit">Entrar</button></form><p class="login-foot">Acesso restrito ao administrador autorizado.</p></section>`;
}
function pageTitle(){return ({dashboard:'Visão geral',games:'Jogos',players:'Participantes',fields:'Gramados',finance:'Pagamentos',settings:'Configurações'})[page]}
function heading(eyebrow,title,sub,action=''){return `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p class="sub">${sub}</p></div><div class="actions">${action}</div></div>`}
function stat(label,value,foot,icon){return `<div class="card"><div class="stat-top"><span>${label}</span><span class="stat-icon">${icon}</span></div><div class="stat-num">${value}</div><div class="stat-foot">${foot}</div></div>`}
function gameOptions(){const selected=rosterGame||upcoming()?.id;return state.games.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(g=>`<option value="${g.id}" ${g.id===selected?'selected':''}>${localDate(g.date)} · ${esc(g.time)}</option>`).join('')}
function pageBody(g){if(page==='dashboard')return dashboard(g);if(page==='games')return gamesPage();if(page==='players')return playersPage();if(page==='fields')return fieldsPage();if(page==='finance')return financePage();return settingsPage(g)}
function dashboard(g){
 const active=state.games.filter(x=>x.status==='open').length, due=state.games.filter(x=>x.status==='open').reduce((s,x)=>s+dueTotal(x),0), total=state.players.filter(p=>p.active).length;
 const latest=state.games.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4);
 const action=`<button class="btn" data-action="export">⇩ Exportar CSV</button><button class="btn primary" data-action="new-game">＋ Novo jogo</button>`;
 return `${heading('PAINEL DO ADMINISTRADOR','Bem-vindo ao Society Gramado!','Acompanhe a agenda, os participantes e a prestação de contas.',action)}${g?`<div class="hero"><div><div class="eyebrow">PRÓXIMO JOGO · ${g.status==='open'?'INSCRIÇÕES ABERTAS':'AGENDADO'}</div><h2>${esc(field(g.fieldId)?.name||'Gramado a definir')}</h2><p>${localDate(g.date)} · ${esc(g.time)} · ${g.players.length} participante${g.players.length===1?'':'s'} na lista</p></div><div class="hero-right"><div class="hero-date">${brl(g.fee)} <span style="font-size:12px;color:#c3d9cc">por jogador</span></div><div class="hero-loc">${g.foodFee?`+ ${brl(g.foodFee)} ${esc(g.foodName||'extra')}`:'Pagamento via PIX'}</div></div></div>`:''}<div class="cards">${stat('Próximos jogos',active,String(state.games.filter(x=>x.date>=today).length)+' no calendário','⚽')}${stat('Participantes ativos',total,'Cadastros no sistema','♙')}${stat('A receber',brl(due),'Jogos com inscrições abertas','＄')}${stat('Gramados',state.fields.length,'Locais cadastrados','▤')}</div><div class="grid-2"><div class="panel"><div class="panel-head"><h3>Agenda recente</h3><button class="copy" data-page="games">Ver calendário →</button></div><div class="table-wrap"><table><thead><tr><th>Jogo</th><th>Local</th><th>Lista</th><th>Status</th></tr></thead><tbody>${latest.map(x=>`<tr><td class="name-cell">${localDate(x.date)}<div class="subcell">${esc(x.time)}</div></td><td>${esc(x.locationLabel||field(x.fieldId)?.name||'A definir')}</td><td>${x.players.length} jogadores</td><td>${gameStatus(x)}</td></tr>`).join('')}</tbody></table></div></div><div class="panel"><div class="panel-head"><h3>Pagamentos do próximo jogo</h3><small>${g?`${paidCount(g)}/${g.players.length} pagos`:''}</small></div>${g?`<div class="progress-row"><span>Taxa do jogo</span><div class="progress"><span style="width:${g.players.length?100*paidCount(g)/g.players.length:0}%"></span></div><b>${g.players.length?Math.round(100*paidCount(g)/g.players.length):0}%</b></div><div class="quick-list">${g.players.slice(0,5).map(p=>`<div class="quick-item"><div class="quick-main"><div class="avatar">${initials(p.name)}</div><div><div class="quick-title">${esc(p.name)}</div><div class="quick-meta">${p.position==='Goleiro'?'Goleiro':'Jogador'}</div></div></div><span class="pill ${p.paid?'paid':'pending'}">${p.paid?'Pago':'Pendente'}</span></div>`).join('')}</div><div style="margin-top:14px"><button class="btn small" data-action="roster" data-id="${g.id}">Gerenciar lista e pagamentos</button></div>`:`<div class="empty">Nenhum próximo jogo cadastrado.</div>`}</div></div>`
}
function gamesPage(){return `${heading('CALENDÁRIO','Jogos','Crie e atualize os jogos semanais, locais e listas de presença.',`<button class="btn primary" data-action="new-game">＋ Agendar jogo</button>`)}<div class="panel"><div class="panel-head"><h3>Todos os jogos</h3><small>${state.games.length} registros</small></div><div class="table-wrap"><table><thead><tr><th>Data e hora</th><th>Gramado</th><th>Jogadores</th><th>Valor</th><th>Em aberto</th><th>Status</th><th>Ações</th></tr></thead><tbody>${state.games.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(g=>`<tr><td class="name-cell">${localDate(g.date)}<div class="subcell">${esc(g.time)}</div></td><td>${esc(g.locationLabel||field(g.fieldId)?.name||'A definir')}</td><td>${g.players.length}</td><td>${brl(g.fee)}${g.foodFee?`<div class="subcell">+ ${brl(g.foodFee)} ${esc(g.foodName||'extra')}</div>`:''}</td><td>${brl(dueTotal(g))}</td><td>${gameStatus(g)}</td><td><div class="inline-actions"><button class="btn small" data-action="roster" data-id="${g.id}">Lista</button><button class="btn small" data-action="edit-game" data-id="${g.id}">Editar</button></div></td></tr>`).join('')}</tbody></table></div></div>`}
function playersPage(){const term=searchTerm.toLocaleLowerCase('pt-BR');const list=state.players.filter(p=>p.name.toLocaleLowerCase('pt-BR').includes(term)||p.phone.includes(term));return `${heading('ELENCO','Participantes','Cadastre jogadores e mantenha os contatos para organizar cada partida.',`<button class="btn primary" data-action="new-player">＋ Adicionar participante</button>`)}<div class="panel"><div class="toolbar"><input class="search" id="search" placeholder="⌕  Buscar por nome ou telefone" value="${esc(searchTerm)}"><small style="color:var(--muted)">${list.length} participantes</small></div><div class="table-wrap"><table><thead><tr><th>Participante</th><th>Telefone</th><th>Jogos na lista</th><th>Status</th><th></th></tr></thead><tbody>${list.map(p=>{const count=state.games.reduce((n,g)=>n+g.players.filter(x=>x.name.toLowerCase()===p.name.toLowerCase()).length,0);return `<tr><td><div class="person"><div class="avatar">${initials(p.name)}</div><div class="name-cell">${esc(p.name)}</div></div></td><td>${p.phone?`<a class="link" href="https://wa.me/${p.phone.replace(/\D/g,'')}" target="_blank">${esc(p.phone)}</a>`:'—'}</td><td>${count}</td><td><span class="pill ${p.active?'paid':'done'}">${p.active?'Ativo':'Inativo'}</span></td><td><button class="btn small" data-action="edit-player" data-id="${p.id}">Editar</button></td></tr>`}).join('')}</tbody></table></div></div>`}
function fieldsPage(){return `${heading('LOCAIS','Gramados','Cadastre os campos, endereços, links de rota e opções em caso de chuva.',`<button class="btn primary" data-action="new-field">＋ Novo gramado</button>`)}<div class="section-grid">${state.fields.map(f=>`<article class="field-card"><div class="field-banner">⚽</div><div class="field-title">${esc(f.name)}</div><div class="field-address">${esc(f.address||'Endereço não informado')}</div>${f.notes?`<p class="sub">${esc(f.notes)}</p>`:''}<div class="field-actions"><div>${f.maps?`<a class="link" href="${esc(f.maps)}" target="_blank">Abrir mapa ↗</a>`:'<span class="sub">Sem localização</span>'}</div><button class="btn small" data-action="edit-field" data-id="${f.id}">Editar</button></div></article>`).join('')}</div>`}
function financePage(){const g=rosterGame?state.games.find(x=>x.id===rosterGame):upcoming();const expected=state.games.reduce((s,x)=>s+x.players.reduce((n,p)=>n+Number(x.fee||0)+(p.foodWanted?Number(x.foodFee||0):0),0),0);const paid=state.games.reduce((s,x)=>s+x.players.reduce((n,p)=>n+(p.paid?Number(x.fee||0):0)+(p.foodWanted&&p.foodPaid?Number(x.foodFee||0):0),0),0);return `${heading('CAIXA DO FUTEBOL','Pagamentos','Acompanhe valores previstos, confirmações e comprovantes dos jogadores.',`<button class="btn" data-action="export">⇩ Exportar CSV</button>`)}<div class="cards">${stat('Total previsto',brl(expected),'Jogos cadastrados','＄')}${stat('Confirmado',brl(paid),'Conforme marcações recebidas','✓')}${stat('Pendente',brl(Math.max(0,expected-paid)),'Aguardando confirmação','◷')}${stat('Chave PIX',state.pix||'—','Clique para copiar','▣')}</div><div class="panel"><div class="toolbar"><select id="finance-game" class="search">${gameOptions()}</select><button class="btn" data-action="copy-pix">▣ Copiar chave PIX</button></div>${g?`<div class="panel-head"><h3>${localDate(g.date)} · ${esc(g.time)} · ${esc(field(g.fieldId)?.name||'Gramado')}</h3><small>Jogo ${brl(g.fee)}${g.foodFee?' + extra '+brl(g.foodFee):''}</small></div><div class="table-wrap"><table><thead><tr><th>Participante</th><th>Jogo</th>${g.foodFee?'<th>Extra</th>':''}<th>Comprovante</th><th>Ação</th></tr></thead><tbody>${g.players.map((p,i)=>`<tr><td class="name-cell">${esc(p.name)}</td><td><span class="pill ${p.paid?'paid':'pending'}">${p.paid?'Pago':'Pendente'}</span></td>${g.foodFee?`<td>${p.foodWanted?`<span class="pill ${p.foodPaid?'paid':'pending'}">🥩 ${p.foodPaid?'Pago':'Pendente'}</span>`:'<span class="pill done">Não pediu</span>'}</td>`:''}<td>${receiptCell(p)}</td><td><button class="btn small" data-action="payment" data-id="${g.id}" data-index="${i}">Registrar</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty">Cadastre um jogo para controlar os pagamentos.</div>`}<div class="note">O sistema registra o status e permite anexar comprovantes de imagem ou PDF. A confirmação do pagamento é feita pelo administrador após conferir o recebimento.</div></div>`}
function settingsPage(){return `${heading('ADMINISTRAÇÃO','Configurações','Defina os dados usados nos avisos de pagamento e confira a conexão do sistema.',`<button class="btn primary" data-action="save-settings">Salvar alterações</button>`)}<div class="grid-2"><div class="panel"><div class="panel-head"><h3>Pagamento via PIX</h3></div><div class="field"><label>Chave PIX (telefone)</label><input id="pix" value="${esc(state.pix)}"></div><div class="field" style="margin-top:12px"><label>Instrução padrão</label><input value="Enviar comprovante ao administrador após o PIX" disabled></div></div><div class="panel"><div class="panel-head"><h3>Sincronização</h3></div><p class="sub">${cloudEnabled?'Login do administrador conectado. Os dados de jogos e pagamentos sincronizam pelo Firestore.':'O projeto abre em modo demonstração e salva os dados neste navegador.'}</p><div class="note">O sistema não usa Firebase Storage. Comprovantes anexados ficam somente neste dispositivo; os registros de pagamento e demais dados continuam sincronizados pelo Firestore.</div><p class="sub" style="margin-top:14px">O plano Spark permanece sem configuração de faturamento. Comprovantes podem ser anexados em imagem ou PDF de até 5 MB.</p></div></div><div class="panel" style="margin-top:15px"><div class="panel-head"><h3>Dados do sistema</h3></div><p class="sub">${state.players.length} participantes · ${state.fields.length} gramados · ${state.games.length} jogos históricos e futuros.</p><button class="btn" data-action="reset-demo">Restaurar dados iniciais desta versão</button></div>`}
function openModal(title,body,submitLabel='Salvar'){document.querySelector('#modal-root').innerHTML=`<div class="modal-backdrop" data-close><form class="modal" id="modalForm"><div class="modal-head"><h2>${title}</h2><button type="button" class="close" data-close>×</button></div><div class="modal-body">${body}</div><div class="modal-foot"><button type="button" class="btn" data-close>Cancelar</button><button type="submit" class="btn primary">${submitLabel}</button></div></form></div>`}
function closeModal(){document.querySelector('#modal-root').innerHTML=''}
function toast(msg){const root=document.querySelector('#toast-root');root.innerHTML=`<div class="toast">${esc(msg)}</div>`;setTimeout(()=>root.innerHTML='',2800)}
function gameForm(g={}){const isEdit=!!g.id;openModal(isEdit?'Editar jogo':'Agendar jogo',`<div class="form-grid"><div class="field"><label>Data *</label><input name="date" type="date" required value="${g.date||''}"></div><div class="field"><label>Horário *</label><input name="time" type="time" required value="${g.time||'14:30'}"></div><div class="field"><label>Gramado</label><select name="fieldId">${state.fields.map(f=>`<option value="${f.id}" ${g.fieldId===f.id?'selected':''}>${esc(f.name)}</option>`).join('')}</select></div><div class="field"><label>Valor do jogo (R$)</label><input name="fee" type="number" min="0" step="0.01" value="${g.fee??20}"></div><div class="field"><label>Extra / churrasco (R$)</label><input name="foodFee" type="number" min="0" step="0.01" value="${g.foodFee||0}"></div><div class="field"><label>Nome do extra</label><input name="foodName" value="${esc(g.foodName||'Churrasco')}"></div><div class="field"><label>Status</label><select name="status"><option value="open" ${g.status==='open'?'selected':''}>Inscrições abertas</option><option value="closed" ${g.status==='closed'?'selected':''}>Lista fechada</option><option value="played" ${g.status==='played'?'selected':''}>Realizado</option></select></div><div class="field"><label>Local alternativo em caso de chuva</label><input name="rainField" value="${esc(g.rainField||'')}"></div></div>`);
 document.querySelector('#modalForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));if(isEdit)Object.assign(g,d,{fee:+d.fee,foodFee:+d.foodFee});else state.games.push({...d,id:'g'+Date.now(),fee:+d.fee,foodFee:+d.foodFee,players:[],maps:'',status:d.status});persist();closeModal();render();toast('Jogo salvo.')};}
function playerForm(p={}){openModal(p.id?'Editar participante':'Novo participante',`<div class="form-grid"><div class="field full"><label>Nome *</label><input name="name" required value="${esc(p.name||'')}"></div><div class="field"><label>Telefone / WhatsApp</label><input name="phone" placeholder="(48) 99999-9999" value="${esc(p.phone||'')}"></div><div class="field"><label>Status</label><select name="active"><option value="true" ${p.active!==false?'selected':''}>Ativo</option><option value="false" ${p.active===false?'selected':''}>Inativo</option></select></div></div>`);document.querySelector('#modalForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));if(p.id)Object.assign(p,d,{active:d.active==='true'});else state.players.push({...d,id:'p'+Date.now(),active:true});persist();closeModal();render();toast('Participante salvo.')};}
function fieldForm(f={}){openModal(f.id?'Editar gramado':'Novo gramado',`<div class="form-grid"><div class="field full"><label>Nome do local *</label><input name="name" required value="${esc(f.name||'')}"></div><div class="field full"><label>Endereço / referência</label><input name="address" value="${esc(f.address||'')}"></div><div class="field full"><label>Link do Google Maps</label><input name="maps" value="${esc(f.maps||'')}"></div><div class="field full"><label>Observações</label><textarea name="notes" rows="3">${esc(f.notes||'')}</textarea></div></div>`);document.querySelector('#modalForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));if(f.id)Object.assign(f,d);else state.fields.push({...d,id:'f'+Date.now()});persist();closeModal();render();toast('Gramado salvo.')};}
function roster(g){rosterGame=g.id;const body=`<div class="toolbar"><select id="add-player" class="search"><option value="">Adicionar participante cadastrado…</option>${state.players.filter(p=>p.active).map(p=>`<option>${esc(p.name)}</option>`).join('')}</select><button class="btn" type="button" id="addToRoster">＋ Adicionar</button></div><div class="table-wrap"><table><thead><tr><th>Nome</th><th>Posição</th><th>Pagamento</th><th>Extra</th><th></th></tr></thead><tbody>${g.players.map((p,i)=>`<tr><td class="name-cell">${esc(p.name)}</td><td><select data-pos="${i}" class="inline-select"><option ${p.position==='Jogador'?'selected':''}>Jogador</option><option ${p.position==='Goleiro'?'selected':''}>Goleiro</option></select></td><td><button class="pill ${p.paid?'paid':'pending'}" data-action="toggle-pay" data-id="${g.id}" data-index="${i}">${p.paid?'Pago':'Pendente'}</button></td><td>${g.foodFee?(p.foodWanted?`<button class="pill ${p.foodPaid?'paid':'pending'}" data-action="toggle-food" data-id="${g.id}" data-index="${i}">🥩 ${p.foodPaid?'Pago':'Pendente'}</button>`:`<button class="btn small" data-action="toggle-food-order" data-id="${g.id}" data-index="${i}">Não pediu · Incluir</button>`):'—'}</td><td><button class="copy" data-action="remove-player" data-id="${g.id}" data-index="${i}">Remover</button></td></tr>`).join('')}</tbody></table></div>`;openModal(`Lista · ${localDate(g.date)} · ${esc(field(g.fieldId)?.name||'Jogo')}`,body,'Concluir');document.querySelector('#modalForm').onsubmit=e=>{e.preventDefault();persist();closeModal();render();toast('Lista atualizada.')};document.querySelector('#addToRoster').onclick=()=>{const name=document.querySelector('#add-player').value;if(name&&!g.players.some(p=>p.name.toLowerCase()===name.toLowerCase())){g.players.push({name,position:'Jogador',paid:false,foodWanted:false,foodPaid:false});roster(g)}};document.querySelectorAll('[data-pos]').forEach(sel=>sel.onchange=()=>g.players[Number(sel.dataset.pos)].position=sel.value)}
function paymentForm(g,i){const p=g.players[i];openModal(`Pagamento · ${esc(p.name)}`,`<div class="form-grid"><div class="field"><label>Valor do jogo</label><input value="${brl(g.fee)}" disabled></div><div class="field"><label>Status do jogo</label><select name="paid"><option value="false" ${!p.paid?'selected':''}>Pendente</option><option value="true" ${p.paid?'selected':''}>Pago</option></select></div>${g.foodFee?`<div class="field"><label>Vai querer ${esc(g.foodName||'extra')}? · ${brl(g.foodFee)}</label><select name="foodWanted"><option value="false" ${!p.foodWanted?'selected':''}>Não pediu</option><option value="true" ${p.foodWanted?'selected':''}>Sim, incluir</option></select></div><div class="field"><label>Pagamento do extra</label><select name="foodPaid"><option value="false" ${!p.foodPaid?'selected':''}>Pendente</option><option value="true" ${p.foodPaid?'selected':''}>Pago</option></select></div>`:''}<div class="field full"><label>Comprovante (imagem ou PDF, até 5 MB)</label><input name="receipt" type="file" accept="image/*,application/pdf"></div>${p.receipt?`<div class="field full">${receiptCell(p)}<button type="button" class="copy" data-action="remove-receipt" data-id="${g.id}" data-index="${i}">Remover comprovante</button></div>`:''}</div><div class="note">O status do pagamento sincroniza pelo Firestore. O arquivo do comprovante fica guardado somente neste dispositivo e navegador.</div>`);document.querySelector('#modalForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;p.paid=form.elements.paid.value==='true';if(form.elements.foodWanted)p.foodWanted=form.elements.foodWanted.value==='true';if(form.elements.foodPaid)p.foodPaid=p.foodWanted&&form.elements.foodPaid.value==='true';const file=form.elements.receipt.files[0];if(file){if(!file.type.startsWith('image/')&&file.type!=='application/pdf'){toast('Escolha uma imagem ou um PDF.');return}try{const key=await saveLocalReceipt(file);p.receipt='localreceipt:'+key}catch(error){toast(error.message||'Não foi possível guardar o arquivo neste dispositivo.');return}}persist();closeModal();render();toast('Pagamento atualizado.')};}
function exportCsv(){const lines=['Data,Horário,Jogo,Participante,Jogo pago,Extra pago,Valor do jogo,Valor extra'];state.games.forEach(g=>g.players.forEach(p=>lines.push([g.date,g.time,field(g.fieldId)?.name||'',p.name,p.paid?'Sim':'Não',p.foodPaid?'Sim':'Não',g.fee,g.foodFee||0].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','))));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}));a.download='pagamentos-futebol-society.csv';a.click();URL.revokeObjectURL(a.href);}

document.addEventListener('click',e=>{
 const pageBtn=e.target.closest('[data-page]');if(pageBtn){page=pageBtn.dataset.page;rosterGame=null;render();return}
 if(e.target.closest('#menuBtn')){document.querySelector('#sidebar').classList.toggle('open');return}
 if(e.target.matches('.modal-backdrop')||e.target.closest('button[data-close]')){closeModal();return}
 const b=e.target.closest('[data-action]');if(!b)return;const act=b.dataset.action,id=b.dataset.id,g=state.games.find(x=>x.id===id),i=Number(b.dataset.index),p=state.players.find(x=>x.id===id),f=state.fields.find(x=>x.id===id);
 if(act==='logout'){signOutAdmin().catch(()=>toast('Não foi possível encerrar a sessão.'));return}if(act==='open-receipt'){openReceipt(b.dataset.receipt);return}if(act==='remove-receipt'){g.players[i].receipt='';persist();paymentForm(g,i);return}if(act==='new-game')gameForm();if(act==='edit-game')gameForm(g);if(act==='new-player')playerForm();if(act==='edit-player')playerForm(p);if(act==='new-field')fieldForm();if(act==='edit-field')fieldForm(f);if(act==='roster')roster(g);if(act==='payment')paymentForm(g,i);if(act==='toggle-pay'){g.players[i].paid=!g.players[i].paid;persist();render()}if(act==='toggle-food'){g.players[i].foodPaid=!g.players[i].foodPaid;persist();render()}if(act==='toggle-food-order'){g.players[i].foodWanted=!g.players[i].foodWanted;if(!g.players[i].foodWanted)g.players[i].foodPaid=false;persist();roster(g)}if(act==='remove-player'){g.players.splice(i,1);persist();roster(g)}if(act==='export')exportCsv();if(act==='copy-pix'){navigator.clipboard?.writeText(state.pix).then(()=>toast('Chave PIX copiada.')).catch(()=>toast('Chave PIX: '+state.pix))}if(act==='save-settings'){state.pix=document.querySelector('#pix').value.replace(/\D/g,'');persist();render();toast('Configurações salvas.')}if(act==='reset-demo'){if(confirm('Restaurar os dados de demonstração? As alterações deste navegador serão substituídas.')){state=structuredClone(initial);persist();render();toast('Dados iniciais restaurados.')}}
});
document.addEventListener('input',e=>{if(e.target.id==='search'){searchTerm=e.target.value;const pos=e.target.selectionStart;render();const input=document.querySelector('#search');input.focus();input.setSelectionRange(pos,pos)}});
document.addEventListener('change',e=>{if(e.target.id==='finance-game'){rosterGame=e.target.value;render()}});
if(!cloudEnabled){render()}else{
 renderLogin();
 watchAuthState(async user=>{
  if(!user){currentUser=null;if(stopDataListener){stopDataListener();stopDataListener=null}state=structuredClone(initial);renderLogin(authMessage);authMessage='';return}
  if(user.uid!==firebaseConfig.adminUid){authMessage='Esta conta não está autorizada para administrar o painel.';await signOutAdmin();return}
  authMessage='';currentUser=user;state=load();render();
  if(stopDataListener)stopDataListener();
  stopDataListener=listenToAppData(data=>{if(data&&Array.isArray(data.games)&&Array.isArray(data.players)){state=data;localStorage.setItem(KEY,JSON.stringify(state));render()}},()=>toast('Falha ao receber dados do Firebase. Confira o banco e as regras.'));
 },()=>renderLogin('Não foi possível verificar a sessão. Tente novamente.'));
}
document.addEventListener('submit',async e=>{
 if(e.target.id!=='loginForm')return;e.preventDefault();
 const form=e.target,button=form.querySelector('button[type=submit]');button.disabled=true;button.textContent='Entrando…';
 try{await signInAdmin(form.elements.email.value.trim(),form.elements.password.value)}
 catch{renderLogin('E-mail ou senha inválidos. Verifique se o usuário já foi criado no Firebase.')}
});
